### ISSUE TITLE
jquery-datetime-editor.js removal from Orchard.JQuery causes nwazet.commerce reports to crash

### ISSUE THREAD

**Issue by bleroy** [bleroy/Nwazet.Commerce#77]
Originally reported by: **Dieter Schüle (Bitbucket: [dpomt](http://bitbucket.org/dpomt), GitHub: [dpomt](http://github.com/dpomt))**

---

nwazet.commerce reports relay on jquery-dateime-editor.js which was removed from orchard.jquery sometime ago:

Author:     Sipke Schoorstra sipke@orchardpros.net#mailto:sipke@orchardpros.net
Date:       11 months ago (25.07.2014 06:18:08)
Commit hash:    4ba6bcdbc0d9ef7fa65e30d6d0cc52b9d5712bb9
Parent(s):  be37ee54dc

Posted this also in Orchard forum (https://github.com/OrchardCMS/Orchard/issues/5385) since I do not know whether it should be fixed there or here.

---
- Bitbucket: https://bitbucket.org/bleroy/nwazet.commerce/issue/75

**Comment by MatteoPiovanelli-Laser** [comment]
I actually found this same issue pulling the master from github. 
I fixed it on a branch, along with a few other changes ito bring everything up to date with the latest Orchard 1.10.
However, I am not making a PR right now, because I noticed that I have local HintPaths in the csproj files. I'll fix that and do a PR later.

**Comment by MatteoPiovanelli-Laser** [comment]
I see what the issue is on my end:

I have an usual folder structure because I keep the non-core modules (meaning, all modules that are not form the Orchard official repo) in a different folder, that is also a different solution and a different git-repo.

I am trying to figure out a way around this, so that the project works in my system, but I can also push stuff and do PRs.

**Comment by MatteoPiovanelli-Laser** [comment]
THis was fixe in #90
